# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=10)),
                ('lugar', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
